general:
  # device to run verifier
  device: cuda
  # Complete verification verifier.
  # "bab": branch and bound with beta-CROWN;
  # "mip": mixed integer programming (MIP) formulation;
  # "bab-refine": branch and bound with intermediate layer bounds computed by MIP.
  complete_verifier: bab
# Example for using customized model and data loader.
# Model and data loader defined in custom_model_data.py
# python abcrown.py --config exp_configs/tutorial_examples/custom_model_data_example.yaml
model:
  # Use the simple_conv_model in "custom_model_data.py".
  name: Customized("2023324114", "simple_conv_model", in_channel=3, out_dim=10)
  path: ./models/2023324114_2.pth
data:
  # Use the cifar10() loader in "custom_model_data.py".
  dataset: Customized("2023324114", "svhn")
  mean: [0.4914, 0.4822, 0.4465]
  std: [0.2023, 0.1994, 0.201]
specification:
  epsilon: 0.00784313725  # 2./255.
attack:
  pgd_restarts: 100
solver:
  batch_size: 2048
  beta-crown:
    iteration: 20
bab:
  timeout: 300
